CREATE DATABASE T_Moda;

USE T_Moda;

CREATE TABLE Marca		
(
	IdMarca		INT PRIMARY KEY IDENTITY
	,Nome		VARCHAR (250) NOT NULL UNIQUE		
);

CREATE TABLE Camiseta
(
	IdCamiseta	INT PRIMARY KEY IDENTITY
	,IdMarca	INT FOREIGN KEY REFERENCES Marca (IdMarca)
);

CREATE TABLE Cores
(
	IdCor		INT PRIMARY KEY IDENTITY
	,Nome		VARCHAR (200) NOT NULL UNIQUE
);

CREATE TABLE Tamanho
(
	IdTamanho	INT PRIMARY KEY IDENTITY 
	,Nome		VARCHAR (200) NOT NULL UNIQUE
);

CREATE TABLE CamisetaCorTamanho
(
	IdCamiseta	INT PRIMARY KEY IDENTITY
	,IdCor		INT FOREIGN KEY REFERENCES Cores (IdCor)
	,IdTamanho	INT FOREIGN KEY REFERENCES Tamanho (IdTamanho)
);